// Code generated by Slice Machine. DO NOT EDIT.

import HomeHero from './HomeHero';
import Resources from './Resources';

export {
	HomeHero,
	Resources,
};

export const components = {
	home_hero: HomeHero,
	resource: Resources,
};
